HW 6
Daniil-Vl/java-backend-2023 pull request #8
Opened 2023-11-10 19:53 UTC by Daniil-Vl

2023-11-24 12:47 UTC, easylaneof requested changes

2023-11-24 12:47 UTC, easylaneof commented on src/test/java/edu/hw6/task2/FileClonerTest.java
> +            Arguments.of(
[note] есть статический метод `arguments`

2023-11-24 12:47 UTC, easylaneof commented on src/test/java/edu/hw6/task2/FileClonerTest.java
> +    private static Stream<Arguments> filenames() {
[note] обычно такие методы называют так: `provideFilenames`

2023-11-24 12:47 UTC, easylaneof commented on src/test/java/edu/hw6/task2/FileClonerTest.java
> +        BASE_PATH.resolve(expectedCopiedFileName).toFile().delete();
вот это надо выносить в `@BeforeEach`

2023-11-24 12:47 UTC, easylaneof commented on src/test/java/edu/hw6/task2/FileClonerTest.java
> +        FileInputStream originalFileIn = new FileInputStream(originalFile);
try-with-resources

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task2/FileCloner.java
> +    }
глобальный совет по методу:

лучше выносить части логики в отдельные методы и давать им понятные имена, тогда будет проще разобраться + переиспользовать код

самый яркий пример -- вот эти строчки, можно было сделать метод аля `copyFiles(File, File)`

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task3/AbstractFilter.java
> +public interface AbstractFilter extends DirectoryStream.Filter<Path> {
Интерфейсы лучше не называть со словом `Abstract`, тут бы подошло `ChainFilter`

UPD: увидел, что это было дано в задании, но просто имей в виду на будущее

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task3/AbstractFilterImpl.java
> +public abstract class AbstractFilterImpl implements AbstractFilter {
из-за имени интерфейса приходится такое городить) `Abstract` и `Impl` это прямые противоположности

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task3/AbstractFilterImpl.java
> +    List<AbstractFilter> filters = new LinkedList<>();
тут не нужно использовать LinkedList. ты не пользуешься его преимуществами (константное добавление / удаление по любому индексу), при этом он кушает больше памяти

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task3/GlobMatchFilter.java
> +        StringBuilder out = new StringBuilder("^");
[note] возможно, было бы проще использовать `replace` 4 раза. работало бы дольше, но вряд ли тебе дадут сильно большой glob

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task3/GlobMatchFilter.java
> +    private static String createRegexFromGlob(String glob) {
документация это хорошо, но тут имя метода описывает, что происходит, дублировать это в комментарии особо нет смысла

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task3/GlobMatchFilter.java
> +    @Override
тоже самое про комментарии из интерфейса

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task3/AbstractFilterImpl.java
> +            result &= filter.accept(entry);
непонятно, зачем ты используешь битовый and. он всегда вычисляет правое значение, даже если левое уже false, т.е. даже если первый фильтр вернул false, ты пойдешь по всей цепочке

2023-11-24 12:47 UTC, easylaneof commented on src/test/java/edu/hw6/task3/AbstractFilterTest.java
> +        }
непонятно, зачем так делать в тесте, пускай тест будет `throws IOException`

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task5/HackerNews.java
> +        String urlString = "https://hacker-news.firebaseio.com/v0/topstories.json";
```suggestion
private static final String URL_STRING = "...";
```

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task5/HackerNews.java
> +
весь этот try нужен только из-за того, что `new URI` кидает исключение. Проще отдельно создать `URI`, а потом создавать `request`

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task5/HackerNews.java
> +            return new long[] {};
непонятно, почему не пробрасываешь исключение дальше, а возвращаешь пустой массив. В try выше ты так не делаешь

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task5/HackerNews.java
> +
тоже самое, что выше написал

вообще, единственное, чем этот блок кода отличается -- это урлом. кандидат на то, чтобы вынести его в отдельный метод

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task5/HackerNews.java
> +            Pattern pattern = Pattern.compile("\"" + "title" + "\"" + ":" + "\"" + "[^\"]*" + "\"");
лучше вынести в статическое поле класса, потому что иначе ты при каждом вызове метода будешь строить регулярку (а это долго)

2023-11-24 12:47 UTC, easylaneof commented on src/test/java/edu/hw6/task5/HackerNewsTest.java
> +        long[] topStoryCodes = HackerNews.hackerNewsTopStories();
[note] в целом нормальный тест, но нужно понимать, что в реальной практике ты не будешь напрямую в тестах делать запросы на сторонние api (они могут упасть, например)

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task6/PortChecker.java
> +}
не нужно оставлять закомментированный код

2023-11-24 12:47 UTC, easylaneof commented on src/main/java/edu/hw6/task6/PortChecker.java
> +                }
если порт неизвестен, его все равно нужно логировать по заданию, ты его пропускаешь

2023-11-24 13:14 UTC, easylaneof commented on src/main/java/edu/hw6/task3/AbstractFilter.java
> +public interface AbstractFilter extends DirectoryStream.Filter<Path> {
твоя реализация 3 задания не соответствует тз

нет статических методов аля `largerThan(100_000)`

2023-11-24 13:18 UTC, easylaneof commented on src/main/java/edu/hw6/task3/MagicInitialIdentifiers.java
> +public class MagicInitialIdentifiers extends AbstractFilterImpl {
тут тоже не такой фильтр имелся в виду
почитай про [magic numbers](https://en.wikipedia.org/wiki/File_format#Magic_number)

2023-11-24 13:23 UTC, easylaneof commented on src/main/java/edu/hw6/task6/PortChecker.java
> +            } catch (IOException ignored) {
видимо, в задании имелась в виду другая логика -- нужно писать про занятые порты (т.е. те, которые выкинули исключение)

2023-11-25 12:56 UTC, Daniil-Vl commented
Поправил код везде, где были замечания. Также 3 задание я полностью переписал с использованием FunctionalInterface. Так получилось гораздо лаконичнее.

2023-11-25 15:50 UTC, easylaneof commented
В след раз делай resolve простых замечаний, пожалуйста

2023-11-25 15:51 UTC, easylaneof commented
> А как стоит тестировать методы, в которых есть вызов к сторонним API, как это было в пятом задании?

Нужно создавать отдельные классы, которые будут ими заниматься, и в тестах подменять их реализацию

https://stackoverflow.com/questions/2128148/what-are-mock-objects-in-java
https://habr.com/ru/articles/444982/

Вам еще расскажут это в лекциях

2023-11-28 08:55 UTC, merged